services:
  - type: web
    name: energy-manager
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn energy_manager.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: energy-manager-db
          property: connectionString

databases:
  - name: energy-manager-db
    plan: free
    databaseName: energy_manager
    user: energy_manager
